name: CI
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - closed
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request
    branches: [develop]
  workflow_dispatch:
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Linter
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Start database container
        run: npm run docker
      - name: Install forever for starting server
        run: npm install -g forever
      - name: Start server
        run: PGHOST=localhost PGUSER=test_user PGDATABASE=test_db PGPASSWORD=test_password PGPORT=5432 forever start ./src/index.js
      - name: Integration tests
        run: npm run integration
      - name: Stop server
        run: forever stopall
